version: '3.9'

services:
    app:
        build: .
        container_name: laravel_app_devops
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        depends_on:
            - postgres
        networks:
            - laravel_network

    postgres:
        image: postgres:15
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: gestion_reservation_l3gl
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mamitaatigh
        ports:
            - "5432:5432"
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge
